### ISSUE TITLE
Data Model of React Native Meteor Redux

### ISSUE THREAD

**Issue by Diwei-Chen** [DesignmanIO/react-native-meteor-redux#30] opened 2017-03-30 23:27 UTC
Hi @JulianKingman , would this be the data model of how this library works?

![untitled diagram](https://cloud.githubusercontent.com/assets/26317142/24530268/99d871d0-15fc-11e7-8651-c9a0e0705f39.png)

**Comment by JulianKingman** [comment] 2017-03-30 23:42
Yep, that's pretty accurate.

**Comment by adamgins** [comment] 2017-03-31 00:07
@JulianKingman what happens now with "App Startup", if there's a connection to Meteor... ie goes it "burn with fire" the redux store/disk and replenish redux/disk?

Ie I expect thats probably the simplest approach (in a very complex online/offline sync/merge/resolve-conflicts world). ie when you're offline you won't be getting any DDP add/change/delete, so when you come back online you need refresh things.

I guess the big question is what happens with conflicts?

BTW, a bit confused on the Realm Branch... is there an overview beyond the very basic setup in the branch's read me, please? ie is this only for new apps that are using Realm from the getGo, or does it replace Redux and can be used with an existing Meteor app?

**Comment by Diwei-Chen** [comment] 2017-03-31 05:27
Thanks, Julian

**Comment by JulianKingman** [comment] 2017-04-03 19:26
@adamgins burn-with-fire would be the simplest, but it's quite expensive to save data, so I'm trying to see if a more intelligent solution is possible.

For conflicts, any records that are different on the app are overwritten by the remote versions. I don't have immediate plans to support write operations, so that shouldn't be a problem.

The realm branch uses realm instead of redux. There are pros and cons to this. It should be faster, but it requires native linking, which you can't do in expo, for example. So long as you install realm properly, you should be able to integrate it. A couple people are having issues with it atm though, and I haven't been able to trace the problem.

**Comment by adamgins** [comment] 2017-04-03 20:23
Thanks. 

As opposed to the burn-with-fire, you'd probably have to check last modified date on each document and maintain some sort of replication log. 

Wondering if we could borrow from Meteor here as it already has this issue solved with minimongo, that said I don't currently know how that works under the covers?

**Comment by JulianKingman** [comment] 2017-04-03 22:46
Checking if a document has changed is not a big problem, the problem is finding out if a document has been removed from the server. The ideal option would know which documents you're subscribed to, and notice if documents are missing. Unfortunately there's no way to tell what subscription brought in a particular document.

**Comment by JulianKingman** [comment] 2017-05-17 11:16
Fixed with version 2.

"uniqueIdentifierName" links the documents to the subscription for purpose of synchronization
When MO goes offline, "things" are populated from offline redux store
When MO comes online again, `added` "things" (ddp) are compared with offline things, ones that don't exist anymore are removed from minimongo and redux.
````javascript
MO.subscribe('uniqueIdentifierName', 'subscriptionName', ...params, callback);
const things = MO.collection('things', 'uniqueIdentifierName').find();
````

**Closed as completed by JulianKingman** 2017-05-17 11:16 UTC
